### ISSUE TITLE
Access Alertmanager with basic auth

### ISSUE THREAD

**Issue by PickingUpPieces** [prymitive/kthxbye#45]
Hi @prymitive,
Thanks a lot for your work! :) 
I have one question: Is there a possibility at the moment to access an alertmanager instance protected with basic auth?

Thanks very much in advance :)

**Comment by prymitive** [comment]
It should work I think, but haven't tested it

**Comment by PickingUpPieces** [comment]
That would be awesome! But how does it work? 😂

**Comment by prymitive** [comment]
I naively assumed that one could just pass `foo:bar@localhost:9093` but no.
Looks like the current usage of https://godoc.org/github.com/go-openapi/runtime/client doesn't allow passing basic auth, need to refactor this.

**Comment by prymitive** [comment]
Replaced `-alertmanager.addr` with `-alertmanager.uri` as it now accepts a full URI as the value.
You can now pass `-alertmanager.uri http://foo:bar@localhost:9093`, it will pass `Authorization: Basic ...` headers.
Will cut a release later

**Comment by PickingUpPieces** [comment]
Thanks a lot :D Just discovered it.

**Comment by xafer337** [comment]
Hi!

I'm trying to use the basic auth functionality, but it keeps crashing:

![image](https://user-images.githubusercontent.com/61606830/196938817-d0de5fee-39bd-4517-abce-f4e47e702585.png)

I'm using this configuration in Docker:
```
  kthxbye:
    container_name: kthxbye
    image: ghcr.io/prymitive/kthxbye:v0.15
    command: 
      - '-alertmanager.uri=http://admin:testpsw@alertmanager:9093'
      - '-extend-with-prefix="ack"'
      - '-extend-by=2h'
      - '-extend-if-expiring-in=5m'
      - '-max-duration=672h' #4 weeks
    user: 1001:1001
    logging:
      options:
        max-size: 50m
    restart: unless-stopped
```

It starts correctly when I remove the basic auth from my alertmanager AND I remove "admin:testpsw@" from the uri on the configuration.
If I keep the basic auth on the uri config but I remove the basic auth from alertmanager, it crashes with the same error. I asume there is something wrong happening with the "alertmanager.uri" command.

Did I configure something wrong?

Thanks!
